macro(get_lib_suffix)

        if(_MBCS)
           if(STATIC_LINK_LIBS)
              if(CMAKE_BUILD_TYPE STREQUAL "Debug")
                 SET(LIB_SUFFIX "d")
              else()
                 SET(LIB_SUFFIX "")
              endif()   
           else()
              if(CMAKE_BUILD_TYPE STREQUAL "Debug")
                 SET(LIB_SUFFIX "d_crtdll")      
              else()
                 SET(LIB_SUFFIX "_crtdll")      
              endif()
           endif()
        else()
           if(STATIC_LINK_LIBS)
              if(CMAKE_BUILD_TYPE STREQUAL "Debug")
                 SET(LIB_SUFFIX "wd")
              else()
                 SET(LIB_SUFFIX "w")
              endif()
           else()
              if(CMAKE_BUILD_TYPE STREQUAL "Debug")
                 SET(LIB_SUFFIX "wd_crtdll")      
              else()
                 SET(LIB_SUFFIX "w_crtdll")      
              endif()
           endif()
        endif()

        message(STATUS "LIB_SUFFIX: " ${LIB_SUFFIX})
endmacro()

